package modelo;
// Generated 14 ene 2025, 9:35:16 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import org.hibernate.Hibernate;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	
	private static final long serialVersionUID = 8746280847929530572L;
	private int id;
	private String nombre;
	private Set matriculacioneses = new HashSet(0);
	private Set moduloses = new HashSet(0);

	public Ciclos() {
	}

	public Ciclos(int id) {
		this.id = id;
	}

	public Ciclos(int id, String nombre, Set matriculacioneses, Set moduloses) {
		this.id = id;
		this.nombre = nombre;
		this.matriculacioneses = matriculacioneses;
		this.moduloses = moduloses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

	public Set getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set moduloses) {
		this.moduloses = moduloses;
	}

	@Override
	public String toString() {
	    // Inicializar las colecciones para evitar problemas de carga perezosa
	    Hibernate.initialize(this.matriculacioneses);
	    Hibernate.initialize(this.moduloses);

	    return "Ciclos{" +
	            "id=" + id +
	            ", nombre='" + nombre + '\'' +
	            ", matriculacioneses=" + (matriculacioneses != null ? matriculacioneses.size() + " items" : "null") +
	            ", moduloses=" + (moduloses != null ? moduloses.size() + " items" : "null") +
	            '}';
	}
	
	

}
